"""The ORM models Alembic compares its migrations against."""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, MetaData, String, Text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

# Without this the database invents constraint names, and an autogenerated
# downgrade then emits `drop_constraint(None, ...)`. Agreed once, at the start:
# changing it later means renaming everything already in the database.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_name)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """One Base per application. It owns the MetaData Alembic compares against."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class Source(Base):
    """A NewsAPI source: cnn, bbc-news, reuters."""

    __tablename__ = "sources"

    id: Mapped[int] = mapped_column(primary_key=True)
    # NewsAPI's own id ("cnn"). Natural key -- upserts match on this.
    slug: Mapped[str] = mapped_column(String(80), unique=True)
    name: Mapped[str] = mapped_column(String(120))

    articles: Mapped[list[Article]] = relationship(back_populates="source")

    def __repr__(self) -> str:
        return f"<Source {self.slug}>"


class Article(Base):
    """One story.

    NewsAPI issues no stable article id, so `url` is the natural key: the same
    story seen twice must land on one row, or every refresh would insert a
    fresh copy of everything on the page.
    """

    __tablename__ = "articles"

    id: Mapped[int] = mapped_column(primary_key=True)
    source_id: Mapped[int] = mapped_column(
        ForeignKey("sources.id", ondelete="CASCADE"), index=True
    )
    url: Mapped[str] = mapped_column(String(1000), unique=True)
    title: Mapped[str] = mapped_column(String(500))
    description: Mapped[str | None] = mapped_column(Text())
    content: Mapped[str | None] = mapped_column(Text())
    image_url: Mapped[str | None] = mapped_column(String(1000))
    author: Mapped[str | None] = mapped_column(String(200))
    # timezone=True: NewsAPI sends UTC with a Z suffix.
    published_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), index=True
    )

    source: Mapped[Source] = relationship(back_populates="articles")

    def __repr__(self) -> str:
        return f"<Article #{self.id} {self.title[:40]!r}>"
