

from __future__ import annotations

from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, MetaData, String, Text, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

# Without this, the database invents names for indexes and constraints, and a
# later autogenerated downgrade emits `drop_constraint(None, ...)` because
# Alembic has no idea what to call the thing it wants to drop. Agreed once, at
# the start of the project -- changing the convention later means renaming
# everything already in the database.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_name)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """One Base per application. It owns the MetaData Alembic compares against."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class Source(Base):
    """A NewsAPI source: cnn, bbc-news, reuters."""

    __tablename__ = "sources"

    id: Mapped[int] = mapped_column(primary_key=True)
    # NewsAPI's own id ("cnn"). Natural key -- upserts match on this.
    slug: Mapped[str] = mapped_column(String(80), unique=True)
    name: Mapped[str] = mapped_column(String(120))

    articles: Mapped[list[Article]] = relationship(back_populates="source")

    def __repr__(self) -> str:
        return f"<Source {self.slug}>"


class Article(Base):
    """One story.

    NewsAPI hands out no stable article id, so `url` is the natural key: the
    same story seen twice must land on one row, or every page refresh would
    insert a fresh copy of everything on it.
    """

    __tablename__ = "articles"

    id: Mapped[int] = mapped_column(primary_key=True)
    source_id: Mapped[int] = mapped_column(
        ForeignKey("sources.id", ondelete="CASCADE"), index=True
    )
    url: Mapped[str] = mapped_column(String(1000), unique=True)
    title: Mapped[str] = mapped_column(String(500))
    description: Mapped[str | None] = mapped_column(Text())
    # NewsAPI truncates this to ~200 chars on the free plan and appends
    # "[+1234 chars]". Kept anyway -- it is what the detail page shows.
    content: Mapped[str | None] = mapped_column(Text())
    image_url: Mapped[str | None] = mapped_column(String(1000))
    author: Mapped[str | None] = mapped_column(String(200))
    # timezone=True: NewsAPI sends UTC with a Z suffix. Storing it naive would
    # make "3 hours ago" wrong by the reader's offset.
    published_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), index=True)
    # fetched_at: Mapped[datetime] = mapped_column(
    #     DateTime(timezone=True), server_default=func.now()
    # )

    source: Mapped[Source] = relationship(back_populates="articles")

    def __repr__(self) -> str:
        return f"<Article #{self.id} {self.title[:40]!r}>"
