"""add books.pages and books.isbn

Приклад ALTER TABLE у SQLite. `op.batch_alter_table` замість звичайного
`op.add_column` -- це `render_as_batch=True` у migrations/env.py: SQLite не вміє
ні DROP COLUMN, ні ADD CONSTRAINT, тому Alembic мовчки створює books заново,
переливає рядки, видаляє стару таблицю й перейменовує нову. На PostgreSQL той
самий код виконався б звичайним ALTER TABLE.

Constraint видаляється за іменем (`uq_books_isbn`) -- воно взялося з
NAMING_CONVENTION у models.py. Без конвенції в downgrade() стояло б None.

Revision ID: 05db6a0966e7
Revises: 29452a75a3a1
Create Date: 2026-08-27 13:16:42.410049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05db6a0966e7'
down_revision: Union[str, Sequence[str], None] = '29452a75a3a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pages', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('isbn', sa.String(length=17), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_books_isbn'), ['isbn'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_books_isbn'), type_='unique')
        batch_op.drop_column('isbn')
        batch_op.drop_column('pages')

    # ### end Alembic commands ###
