"""The ORM models Alembic compares its migrations against."""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, MetaData, String, Text, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

# Without this the database invents constraint names, and an autogenerated
# downgrade then emits `drop_constraint(None, ...)`. Agreed once, at the start.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_name)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """One Base per application. It owns the MetaData Alembic reads."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class Source(Base):
    """A NewsAPI source: cnn, bbc-news, reuters."""

    __tablename__ = "sources"

    id: Mapped[int] = mapped_column(primary_key=True)
    # NewsAPI's own id ("cnn"). Natural key -- upserts match on this.
    slug: Mapped[str] = mapped_column(String(80), unique=True)
    name: Mapped[str] = mapped_column(String(120))

    articles: Mapped[list[Article]] = relationship(back_populates="source")

    def __repr__(self) -> str:
        return f"<Source {self.slug}>"


class Article(Base):
    """One story. NewsAPI issues no stable id, so `url` is the natural key."""

    __tablename__ = "articles"

    id: Mapped[int] = mapped_column(primary_key=True)
    source_id: Mapped[int] = mapped_column(
        ForeignKey("sources.id", ondelete="CASCADE"), index=True
    )
    url: Mapped[str] = mapped_column(String(1000), unique=True)
    title: Mapped[str] = mapped_column(String(500))
    description: Mapped[str | None] = mapped_column(Text())
    content: Mapped[str | None] = mapped_column(Text())
    image_url: Mapped[str | None] = mapped_column(String(1000))
    author: Mapped[str | None] = mapped_column(String(200))
    # timezone=True: NewsAPI sends UTC with a Z suffix.
    published_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), index=True
    )

    source: Mapped[Source] = relationship(back_populates="articles")

    def __repr__(self) -> str:
        return f"<Article #{self.id} {self.title[:40]!r}>"


class User(Base):
    """A reader. Nothing authenticates here, so there is no password column."""

    __tablename__ = "users"

    id: Mapped[int] = mapped_column(primary_key=True)
    username: Mapped[str] = mapped_column(String(50), unique=True)
    email: Mapped[str] = mapped_column(String(150), unique=True)

    def __repr__(self) -> str:
        return f"<User {self.username}>"


class LikedArticle(Base):
    """One (user, article) like.

    No relationship()/secondary= on either side -- liked-article reads go
    through explicit Repository joins. The composite primary key is what makes
    a like idempotent at the schema level: the same pair cannot exist twice.
    """

    __tablename__ = "liked_articles"

    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), primary_key=True
    )
    article_id: Mapped[int] = mapped_column(
        ForeignKey("articles.id", ondelete="CASCADE"), primary_key=True
    )
    liked_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    def __repr__(self) -> str:
        return f"<LikedArticle user={self.user_id} article={self.article_id}>"
